---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.3.0


jobs:
  test:
    # Whenever the Go version is updated here, .travis.yml and .promu.yml
    # should also be updated.
    docker:
    - image: circleci/golang:1.13

    steps:
    - prometheus/setup_environment
    - run: make
    - prometheus/store_artifact:
        file: alertmanager-irc-relay 

workflows:
  version: 2
  alertmanager-irc-relay:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - prometheus/publish_release:
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
